# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'DishemMerchant' do
    pod 'Alamofire', '~> 3.4.1'
    pod 'SCLAlertView', '~> 0.6'
end

