# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DishemMerchant' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DishemMerchant
    pod 'Alamofire', '~> 4.0’
    pod 'SCLAlertView', '~> 0.6'

end
